apiVersion: v1
kind: Service
metadata:
  name: scaletestapp-service
  labels:
    prometheus-monitored: "true"
spec:
  type: NodePort
  selector:
    app: scaletestapp
  ports:
    - name: http
      port: 8080
      targetPort: 8080

